// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.924
package layout

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "blog-site/views/components"

func Content() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = ContentStyle().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"content\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for i := 0; i < 8; i++ {
			templ_7745c5c3_Err = components.Card(components.NewsLetter{
				Title: "Новость",
				Text: `
                Люди много столетий лечат артрит, подагру, астму, экзему, заболевания печени, желчного пузыря, сердца… Оно помогает восстановить организм после тяжелых болезней!
                Вы чувствовали, что ваш ум и тело устали? Знайте, что есть мощная и ароматная трава, способная обеспечить необходимую энергию. Он хорошо растёт в теплом климате и широко используется в качестве приправы. Люди много столетий лечат проблемы со здоровьем используя целебную силу розмарина. Вот лишь некоторые преимущества этого удивительного растения: — Розмарин улучшает работу сердца и кровообращение:
                Он имеет антисклеротические свойства, снижает уровень холестерина. Исследования доказали, что это растение полезно после тяжелых болезней, особенно для пожилых людей с нарушением мозгового кровообращения.
                Для улучшения мозгового кровообращения и улучшения работу сердца рекомендуется применять розмарин так:
                1 чайную ложку листьев залить 2 стаканами кипятка, настоять 30 мин в термосе, затем процедить. Принимать по 1-2 столовых ложки 3 раза в день до еды.
                - Розмарин омолаживает клетки кожи: Он увлажняет кожу, уменьшает морщины, активизирует циркуляцию крови, восстанавливает эластичность кожи, снимает отеки, улучшает цвет лица, устраняет пигментные пятна.
                Рекомендуется пить розмариновый чай, добавлять эфирное масло розмарина в крема и маски, а также протирать лицо отваром розмарина.
                — уменьшает боли в суставах, устраняет воспаление и заживляет Особенно полезен розмарин для устранения воспалительных процессов в организме, поэтому он полезен при различных заболеваниях суставов, дыхательных путей и для лечения ран и язв.
                Улучшает здоровье мозга Это связано с тем, что розмарин увеличивает приток крови к голове.
                Трава содержит соединения, которые предотвращают деградацию важного нейротрансмиттера, способного обеспечить хорошую память.
                — Помощь против усталости надпочечников и стресса
                Розмарин прекрасен, потому что он успокаивает гормоны стресса и улучшает настроение. Розмарин не только возобновляет энергию, но и расслабляет тело и ум.
                — Стимулирует рост волос Это связано с тем, что розмарин улучшает кровообращение.
                -От ожирения Розмарин помогает похудеть за счет ускорения расщепления жиров и снижения аппетита. Более эффективен он вместе с травой полыни, шалфея и цветками терна. Смешайте травы в равных количествах и приготовьте чай из 1 чайной ложки смеси трав и 300 мл кипятка. Настоять 25 минут, процедить. Пить по 150 мл трижды в сутки 21 день за 30 минут до еды.
                Вы можете использовать целебную силу розмарина несколькими способами:
                Используйте эфирное масло розмарина: вдыхайте аромат, добавляйте в аромалампу, в шампуни, крема и маски для ухода за кожей и волосами. Употребляйте чай: рекомендуется выпивать 1-2 чашки розмаринового чая каждый день. Особенно хорошо пить такой чай вечером перед сном.
                Розмариновый чай употребляет также при диабете, заболеваниях печени, желчного пузыря, инфаркте миокарда.
                Розмарин прекрасно растёт в комнатных условиях. Для этого лучше всего взять веточку взрослого растения, поместить в банку с водой для развития корней, затем посадить и обеспечить доступ свежего воздуха и солнечных лучей. Нельзя использовать рецепты с розмарином для лечения детей до 12 лет, при эпилептических припадках, беременности. Розмарин на некоторое время повышает давление, поэтому его не рекомендуется применять и при гипертонии 2-3 степени.
            `,
				PictureURL: "./public/images/food/1.png",
				Author:     components.User{Name: "Вася Пупкин", PictureURL: "./public/images/user1.jpg"},
				Date:       "5.08.2025 10:38",
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func ContentStyle() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<style>\n        .content {\n            display: grid;\n            grid-template-columns: 25% 25% 25% 25%;\n            grid-auto-flow: dense;\n            justify-items: center;\n        }\n    </style>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
